// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ThetisData.Context;

#nullable disable

namespace ThetisData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921205036_DropColumnsFromLogs")]
    partial class DropColumnsFromLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("THETIS_ATIVO_VARIAVEL_MACRO", b =>
                {
                    b.Property<int>("ID_ATIVO")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ID_VARIAVEL")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID_ATIVO", "ID_VARIAVEL");

                    b.HasIndex("ID_VARIAVEL");

                    b.ToTable("THETIS_ATIVO_VARIAVEL_MACRO", (string)null);
                });

            modelBuilder.Entity("ThetisModel.Entities.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ATIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtivoSistema")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ATIVO_SISTEMA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("LiquidezDias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LIQUIDEZ_DIAS");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_RISCO")
                        .HasComment("1=Conservador, 2=Moderado, 3=Agressivo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("RentabilidadeEsperada")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("RENTABILIDADE_ESPERADA");

                    b.Property<decimal>("TaxaAdministracao")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TAXA_ADMINISTRACAO");

                    b.Property<int>("TipoAtivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_ATIVO")
                        .HasComment("1=RendaFixa, 2=RendaVariavel, 3=Fundos, 4=CriptoMoedas, 5=Commodities");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("VALOR_MINIMO");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_ATIVO_CODIGO");

                    b.ToTable("THETIS_ATIVOS");
                });

            modelBuilder.Entity("ThetisModel.Entities.AvaliacaoCarteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AVALIACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarteiraRecomendadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARTEIRA");

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("COMENTARIOS");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AVALIACAO");

                    b.Property<string>("ImplementouRecomendacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("IMPLEMENTOU_RECOMENDACAO");

                    b.Property<string>("MotivoNaoImplementacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MOTIVO_NAO_IMPLEMENTACAO");

                    b.Property<int>("NotaAdequacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA_ADEQUACAO");

                    b.Property<int>("NotaExplicacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA_EXPLICACAO");

                    b.Property<int>("NotaGeral")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA_GERAL");

                    b.Property<decimal?>("PercentualImplementado")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_IMPLEMENTADO");

                    b.Property<string>("Recomendaria")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("RECOMENDARIA");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraRecomendadaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("THETIS_AVALIACOES_CARTEIRA");
                });

            modelBuilder.Entity("ThetisModel.Entities.CarteiraRecomendada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARTEIRA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprovadaCliente")
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("APROVADA_CLIENTE");

                    b.Property<string>("Ativa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ATIVA");

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_APROVACAO");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_GERACAO");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXPLICACAO");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_RISCO")
                        .HasComment("1=Conservador, 2=Moderado, 3=Agressivo");

                    b.Property<string>("NomeCarteira")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME_CARTEIRA");

                    b.Property<int>("Objetivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OBJETIVO")
                        .HasComment("1=CurtoPrazo, 2=MedioPrazo, 3=LongoPrazo, 4=Aposentadoria, 5=ReservaEmergencia");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRAZO_MESES");

                    b.Property<decimal>("RentabilidadeEsperada")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("RENTABILIDADE_ESPERADA");

                    b.Property<decimal>("ScoreAdequacao")
                        .HasColumnType("NUMBER(3,2)")
                        .HasColumnName("SCORE_ADEQUACAO");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("Ativa")
                        .HasDatabaseName("IX_CARTEIRA_ATIVA");

                    b.HasIndex("ClienteId", "DataGeracao")
                        .HasDatabaseName("IX_CARTEIRA_CLIENTE_DATA");

                    b.ToTable("THETIS_CARTEIRAS_RECOMENDADAS");
                });

            modelBuilder.Entity("ThetisModel.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NCHAR(11)")
                        .HasColumnName("CPF")
                        .IsFixedLength();

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<int>("ObjetivoPrincipal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OBJETIVO_PRINCIPAL")
                        .HasComment("1=CurtoPrazo, 2=MedioPrazo, 3=LongoPrazo, 4=Aposentadoria, 5=ReservaEmergencia");

                    b.Property<int>("PerfilRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERFIL_RISCO")
                        .HasComment("1=Conservador, 2=Moderado, 3=Agressivo");

                    b.Property<int>("PrazoInvestimentoMeses")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRAZO_INVESTIMENTO");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("RENDA_MENSAL");

                    b.Property<decimal>("ValorDisponivel")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("VALOR_DISPONIVEL");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_CLIENTE_CPF");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_CLIENTE_EMAIL");

                    b.ToTable("THETIS_CLIENTES");
                });

            modelBuilder.Entity("ThetisModel.Entities.HistoricoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtivoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ATIVO");

                    b.Property<int?>("CarteiraRecomendadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORIGEM_RECOMENDACAO");

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_OPERACAO");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<decimal?>("ImpostoRenda")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("IMPOSTO_RENDA");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<decimal?>("PrecoUnitario")
                        .HasColumnType("NUMBER(15,6)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("NUMBER(15,6)")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal?>("RentabilidadeObtida")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("RENTABILIDADE_OBTIDA");

                    b.Property<decimal?>("TaxaCorretagem")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("TAXA_CORRETAGEM");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_OPERACAO");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("VALOR_OPERACAO");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("CarteiraRecomendadaId");

                    b.HasIndex("TipoOperacao")
                        .HasDatabaseName("IX_HISTORICO_TIPO");

                    b.HasIndex("ClienteId", "DataOperacao")
                        .HasDatabaseName("IX_HISTORICO_CLIENTE_DATA");

                    b.ToTable("THETIS_HISTORICO_INVESTIMENTOS");
                });

            modelBuilder.Entity("ThetisModel.Entities.ItemCarteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ITEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ATIVO");

                    b.Property<int>("CarteiraRecomendadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARTEIRA");

                    b.Property<DateTime>("DataIncluido")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INCLUIDO");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("JUSTIFICATIVA");

                    b.Property<decimal>("PercentualCarteira")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_CARTEIRA");

                    b.Property<int>("Prioridade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRIORIDADE");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("NUMBER(15,6)")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("RentabilidadeEsperada")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("RENTABILIDADE_ESPERADA");

                    b.Property<decimal>("ValorInvestimento")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("VALOR_INVESTIMENTO");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.HasIndex("CarteiraRecomendadaId");

                    b.ToTable("THETIS_ITENS_CARTEIRA");
                });

            modelBuilder.Entity("ThetisModel.Entities.LogRecomendacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarteiraRecomendadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CARTEIRA");

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PROCESSAMENTO");

                    b.Property<string>("ErroMensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("ERRO_MENSAGEM");

                    b.Property<string>("ParametrosEntrada")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("PARAMETROS_ENTRADA");

                    b.Property<string>("ResultadoAlgoritmo")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("RESULTADO_ALGORITMO");

                    b.Property<string>("Sucesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("SUCESSO");

                    b.Property<int>("TempoProcessamentoMs")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TEMPO_PROCESSAMENTO");

                    b.Property<string>("VersaoAlgoritmo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("VERSAO_ALGORITMO");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraRecomendadaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataProcessamento")
                        .HasDatabaseName("IX_LOG_DATA");

                    b.ToTable("THETIS_LOGS_RECOMENDACAO");
                });

            modelBuilder.Entity("ThetisModel.Entities.VariavelMacroeconomica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VARIAVEL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODIGO");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REFERENCIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FonteDados")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FONTE_DADOS");

                    b.Property<string>("ImpactoInvestimentos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMPACTO_INVESTIMENTOS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Tendencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TENDENCIA");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.Property<decimal?>("ValorAnterior")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("VALOR_ANTERIOR");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("VALOR_ATUAL");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_VARIAVEL_CODIGO");

                    b.HasIndex("DataAtualizacao")
                        .HasDatabaseName("IX_VARIAVEL_DATA");

                    b.ToTable("THETIS_VARIAVEIS_MACROECONOMICAS");
                });

            modelBuilder.Entity("THETIS_ATIVO_VARIAVEL_MACRO", b =>
                {
                    b.HasOne("ThetisModel.Entities.Ativo", null)
                        .WithMany()
                        .HasForeignKey("ID_ATIVO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ATIVO_VAR_ATIVO");

                    b.HasOne("ThetisModel.Entities.VariavelMacroeconomica", null)
                        .WithMany()
                        .HasForeignKey("ID_VARIAVEL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ATIVO_VAR_VARIAVEL");
                });

            modelBuilder.Entity("ThetisModel.Entities.AvaliacaoCarteira", b =>
                {
                    b.HasOne("ThetisModel.Entities.CarteiraRecomendada", "CarteiraRecomendada")
                        .WithMany()
                        .HasForeignKey("CarteiraRecomendadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AVALIACAO_CARTEIRA");

                    b.HasOne("ThetisModel.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AVALIACAO_CLIENTE");

                    b.Navigation("CarteiraRecomendada");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ThetisModel.Entities.CarteiraRecomendada", b =>
                {
                    b.HasOne("ThetisModel.Entities.Cliente", "Cliente")
                        .WithMany("CarteirasRecomendadas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CARTEIRA_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ThetisModel.Entities.HistoricoInvestimento", b =>
                {
                    b.HasOne("ThetisModel.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_HISTORICO_ATIVO");

                    b.HasOne("ThetisModel.Entities.CarteiraRecomendada", "CarteiraRecomendada")
                        .WithMany()
                        .HasForeignKey("CarteiraRecomendadaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_HISTORICO_CARTEIRA");

                    b.HasOne("ThetisModel.Entities.Cliente", "Cliente")
                        .WithMany("HistoricoInvestimentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HISTORICO_CLIENTE");

                    b.Navigation("Ativo");

                    b.Navigation("CarteiraRecomendada");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ThetisModel.Entities.ItemCarteira", b =>
                {
                    b.HasOne("ThetisModel.Entities.Ativo", "Ativo")
                        .WithMany("ItensCarteira")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_ATIVO");

                    b.HasOne("ThetisModel.Entities.CarteiraRecomendada", "CarteiraRecomendada")
                        .WithMany("Itens")
                        .HasForeignKey("CarteiraRecomendadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ITEM_CARTEIRA");

                    b.Navigation("Ativo");

                    b.Navigation("CarteiraRecomendada");
                });

            modelBuilder.Entity("ThetisModel.Entities.LogRecomendacao", b =>
                {
                    b.HasOne("ThetisModel.Entities.CarteiraRecomendada", "CarteiraRecomendada")
                        .WithMany()
                        .HasForeignKey("CarteiraRecomendadaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_LOG_CARTEIRA");

                    b.HasOne("ThetisModel.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LOG_CLIENTE");

                    b.Navigation("CarteiraRecomendada");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ThetisModel.Entities.Ativo", b =>
                {
                    b.Navigation("ItensCarteira");
                });

            modelBuilder.Entity("ThetisModel.Entities.CarteiraRecomendada", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ThetisModel.Entities.Cliente", b =>
                {
                    b.Navigation("CarteirasRecomendadas");

                    b.Navigation("HistoricoInvestimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
